color: null
fieldLayouts:
  a1afe556-429c-4e11-8a4b-90c0b79f2d3f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-11-22T09:36:09+00:00'
            elementCondition: null
            fieldUid: e2e222ba-6107-4ebe-ba6f-c26cc3a40dd8 # Subtext
            handle: null
            includeInCards: false
            instructions: null
            label: 'List Item'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7aaf20b4-2444-4e0f-a210-8a00b7423c34
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 88f1ff34-aab1-4e4c-b617-334792b3f8c0
        userCondition: null
handle: listItem
hasTitleField: false
icon: ''
name: 'List Item'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
